### ISSUE TITLE
Upgrade action to use Node.js 16 in order to supress deprecation warnings.

### ISSUE THREAD

**Issue by cpswan** [Co-qn/google-chat-notification#19]
Workflows that use this action are showing the following deprecation warning:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: https://github.com/Co-qn/google-chat-notification/commit/b9227d9daa4638c9782a5bd16c4abb86268127a1

![image](https://user-images.githubusercontent.com/478926/204258434-7beb7ad0-7fde-479e-8a65-755e8c1a0f02.png)

**Comment by Co-qn** [comment]
@cpswan Thank you very much. I will respond as soon as I can find the time.

**Comment by cpswan** [comment]
@Co-qn I'm happy to put together a PR if that helps things along?

I was concerned that you haven't been very active on GitHub for a while (and that there are a few long standing Dependabot PRs on this repo), but it's great to get such a quick response from you, and I'd always rather help an upstream maintainer than go off on my own.

**Comment by cpswan** [comment]
Fixed by #20 

Many thanks @Co-qn I can confirm that I'm not seeing deprecation warnings on runs with the new release.
